let age = '27';
let phone = '123 456 7890';
let streetName = 'Fake Street';
let streetNumber = '123';
let template_age = `I'm ${age} years old`;
let template_phone = `My phone number is: ${phone}`;
let template_street = `I live on ${streetNumber} ${streetName}`;
console.log(template_age);
console.log(template_phone);
console.log(template_street);